spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway-service         # 路由id
          uri: https://www.baidu.com   # uri
          order: 0
          predicates:
#            - After=2020-03-01T00:00:00+08:00[Asia/Shanghai]
#            - Before=2020-03-01T00:00:00+08:00[Asia/Shanghai]
#            - Between=2020-02-06T00:00:00+08:00[Asia/Shanghai],2020-03-01T00:00:00+08:00[Asia/Shanghai]
#            - Cookie=sessionId, test
#            - Header=X-request-Id, \d+
#            - Host=**.baidu.com
            - Method=GET
#            - Path=/customer/{segment},/foo/{segment}
            - RemoteAddr=192.168.0.1/0
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar

server:
  port: 15000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ #服务注册中心的地址
logging:
  level:
    org.springframework.cloud.gateway: debug # 调整日志级别

