spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/ # \u6307\u5B9A Eureka \u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
server:
  port: 9000 # \u5206\u522B\u4E3A 9000\u30019001\u30019002

eureka-consumer:
  riboon:
    NFLoadBalancerRuleClassName: