server:
  port: 13000

spring:
  application:
    name: config-client
  rabbitmq:       # rabbitmq的相关配置。
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true # 开启消息跟踪

# springboot1.5x 以上默认开通了安全认证，所以需要添加这个配置。用于config client端刷新配置文件的url
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
