server:
  port: 13000
spring:
  application:
    name: config-client

# springboot1.5x\u5F00\u59CB\uFF0C\u9ED8\u8BA4\u5F00\u901A\u4E86\u5B89\u5168\u8BA4\u8BC1
management:
  endpoints:
    web:
      exposure:
        include: refresh
